import "@/styles/globals.css"

import type { Metadata } from "next"
import { cn } from "@heroui/react"
import { Geist, Geist_Mono } from "next/font/google"
import { NuqsAdapter } from "nuqs/adapters/next/app"

import { HeroUIProvider } from "@/providers/hero-ui-provider"
import { ThemeProvider } from "@/providers/theme-provider"
import { QueryProvider } from "@/providers/query-provider"

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"]
})

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          "font-sans antialiased"
        )}
      >
        <QueryProvider>
          <ThemeProvider>
            <HeroUIProvider>
              <NuqsAdapter>{children}</NuqsAdapter>
            </HeroUIProvider>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
